Remove qtwebkit

diff --git a/mythtv/configure b/mythtv/configure
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -6530,16 +6530,16 @@ case $target_os in
         ;;
 esac
 
-if $(pkg-config --exists Qt5WebKit) || $(pkg-config --exists QtWebKit) ; then
-    enable qtwebkit
-else
-    check_ecxx ${qt_inc} ${qt_inc}/QtCore <<EOF && enable qtwebkit
-#include <QtWebKit/QtWebKit>
-int main(void){ return 0; }
-EOF
-fi
+#if $(pkg-config --exists Qt5WebKit) || $(pkg-config --exists QtWebKit) ; then
+#    enable qtwebkit
+#else
+#    check_ecxx ${qt_inc} ${qt_inc}/QtCore <<EOF && enable qtwebkit
+##include <QtWebKit/QtWebKit>
+#int main(void){ return 0; }
+#EOF
+#fi
 
-enabled qtwebkit || die "Error! QtWebkit headers not found"
+#enabled qtwebkit || die "Error! QtWebkit headers not found"
 
 if $(pkg-config --exists Qt5Script) || $(pkg-config --exists QtScript) ; then
     enable qtscript
